import { ResumeData } from '../types/Resume';

const SHARED_CONTACT = {
  phone: '+5512996569230',
  email: 'andhersonsantos@gmail.com',
  linkedin: 'https://www.linkedin.com/in/andherson/',
  location: 'Caraguatatuba – SP – Brasil',
  instagram: 'https://www.instagram.com/andhersonsantos/',
  github: 'https://github.com/andhersonsantos/',
};

const SKILLS_PT = [
  {
    title: 'Arquitetura & Estratégia',
    skills: [
      'Micro-frontends',
      'Monorepo (Nx/Turborepo)',
      'System Design',
      'Cloud-Native (AWS)',
      'Otimização CI/CD',
      'Estratégias de Migração',
    ],
  },
  {
    title: 'Linguagens & Tech Stack',
    skills: [
      'JavaScript',
      'TypeScript',
      'React.js',
      'Next.js',
      'Vue.js',
      'Node.js',
      'GraphQL',
    ],
  },
  {
    title: 'Qualidade & Observabilidade',
    skills: [
      'Cypress',
      'Playwright',
      'Datadog',

      'Performance Tuning',
      'Feature Flags',
      'A/B Testing',
    ],
  },
  {
    title: 'Liderança',
    skills: [
      'Mentoria Técnica',
      'Criação de RFCs',
      'Gestão de Stakeholders',
      'Padrões de Engenharia',
      'Metodologias Ágeis',
    ],
  },
];

const SKILLS_EN = [
  {
    title: 'Architecture & Strategy',
    skills: [
      'Micro-frontends',
      'Monorepo (Nx/Turborepo)',
      'System Design',
      'Cloud-Native (AWS)',
      'CI/CD Optimization',
      'Migration Strategies',
    ],
  },
  {
    title: 'Languages & Tech Stack',
    skills: [
      'JavaScript',
      'TypeScript',
      'React.js',
      'Next.js',
      'Vue.js',
      'Node.js',
      'GraphQL',
    ],
  },
  {
    title: 'Quality & Observability',
    skills: [
      'Cypress',
      'Playwright',
      'Datadog',
      'Performance Tuning',
      'Feature Flags',
      'A/B Testing',
    ],
  },
  {
    title: 'Leadership',
    skills: [
      'Technical Mentoring',
      'RFC Creation',
      'Stakeholder Management',
      'Engineering Standards',
      'Agile Methodologies',
    ],
  },
];

export const DATA_PT: ResumeData = {
  name: 'Andherson Antunes',
  role: 'Staff Software Engineer Frontend | Technical Lead',
  contact: SHARED_CONTACT,
  summary: [
    `Com mais de 10 anos de experiência em tecnologia, hoje atuo na manutenção e evolução do fluxo de aquisição de planos de ZAP e Vivareal no Grupo OLX, 
    eliminando fricções na jornada do usuário e desenhando soluções técnicas robustas que sustentam o crescimento do produto.`,
    `Nos momentos offline, recarrego as energias pedalando, fotografando e curtindo momentos com meus dois filhos =)`,
  ],
  skillCategories: SKILLS_PT,
  experience: [
    {
      isLocked: true,
      company: 'VIDA',
      role: 'Pai',
      period: 'Ago 2021 – Atual',
      location: 'Presencial',
      summary: [
        "Gerenciando o 'projeto' mais complexo e valioso da vida: o futuro de dois seres humanos.",
        "Responsável pelo 'deploy' diário de valores, 'debugging' de birras e garantia de alta disponibilidade de afeto.",
        'É a única posição onde os incidentes em produção ensinam mais sobre inteligência emocional e negociação do que qualquer reunião de board.',
      ],
      techStack: [
        'Inteligência Emocional',
        'Negociação',
        'Gestão de Crise',
        'Ensinamento por exemplo',
      ],
    },
    {
      company: 'GRUPO OLX BRASIL',
      role: 'Staff Software Engineer / Front-end Tech Lead',
      period: 'Fev 2024 – Atual',
      location: 'Remoto',
      summary: [
        'Ponto focal técnico da vertical de Imóveis (ZAP / Vivareal), conectando estratégia de negócios e execução de engenharia.',
        'Disseminação de boas práticas e fomentando uma cultura "quality-first", diretrizes arquiteturais em vários projetos',
        'Mentoria de engenheiros, promovendo autonomia, documentação e testes automatizados.',
      ],
      techStack: [
        'React.js',
        'Next.js',
        'Vue.js',
        'TypeScript',
        'Micro-frontends',
        'Monorepo',
        'AWS',
        'Datadog',
        'Cypress',
      ],
    },
    {
      company: 'BIONEXO',
      role: 'Tech Lead | Specialist Front-end Developer',
      period: 'Jul 2023 – Fev 2024',
      location: 'Remoto',
      summary: [
        'Focado em desenhar arquiteturas de aplicações front-end, estabelecer padrões de desenvolvimento e mentoria.',
        'Consolidação de clientes de múltiplos sistemas legados e países em um produto global unificado, reduzindo complexidade e custos de manutenção.',
      ],
      techStack: [
        'React.js',
        'Next.js',
        'TypeScript',
        'Playwright',
        'Java',
        'Azure',
        'i18n',
      ],
    },
    {
      company: 'BIONEXO',
      role: 'Systems Analyst (Front-end Engineer)',
      period: 'Set 2019 – Jul 2023',
      location: 'Remoto',
      summary: [
        'Evolução de sistemas legados multi-plataformas.',
        'Colaboração direta com Produto e QA para definir requisitos de sistemas.',
        'Agile Leader: Responsável pelo acompanhamento de KPIs de vazão da squad e promoção de metodologias Ágeis (Scrum, Kanban, XP).',
      ],
      techStack: [
        'React.js',
        'JSP',
        'jQuery',
        'Ruby on Rails',
        'AWS',
        'Bitbucket',
      ],
    },
    {
      isLocked: true,
      company: 'BADEKAR CENTRO AUTOMOTIVO',
      role: 'Gerente Comercial',
      period: 'Out 2018 – Ago 2019',
      location: 'Caraguatatuba, SP',
      summary: [
        'Liderança na transformação digital do negócio, implementando processos de Customer Experience e Marketing Digital. Atuação técnica na modernização da gestão de estoque, criando integrações entre sistemas legados e novas interfaces web.',
        'Engenharia reversa e desenvolvimento de middleware para interceptação de dados em sistema proprietário (Delphi), automatizando a gestão de estoque, além do desenvolvimento full-stack do website institucional e sistema de histórico veicular.',
      ],
      techStack: [
        'Marketing Digital',
        'Desenvolvimento Web',
        'Customer Experience',
        'Middleware',
      ],
    },
    {
      isLocked: true,
      company: 'BANCO BRADESCO SA',
      role: 'De escriturário a Gerente Prime',
      period: 'Out 2011 – Set 2018',
      location: 'Caraguatatuba, SP',
      summary: [
        'Atuação em ambiente de alta pressão e regulamentação, onde o foco era a resolução ágil de problemas e a experiência do cliente.',
        'A vivência com públicos de diversas classes sociais e momentos de vida me ensinou a ter empatia, resiliência e clareza na comunicação, pilares que sustento na minha liderança técnica.',
      ],
      techStack: [
        'Negociação',
        'Gestão de Conflitos',
        'Vendas Consultivas',
        'Comunicação Estratégica',
        'Atendimento ao Cliente',
        'Liderança de Equipe',
      ],
    },
    {
      company: 'Beto Biagi Marketing & Comunicação',
      role: 'Full Stack Developer',
      period: 'Ago 2008 - Dez 2009',
      location: 'Atibaia, SP',
      summary: [
        'Atuei como líder técnico para os clientes da agência, integrando Engenharia, Design e Operações. Um destaque foi a gestão da presença digital da Coomex, ativo de energia adquirido pelo BTG Pactual.',
        'Além do desenvolvimento Full Stack, liderei iniciativas de UI/UX e performance técnica. Implementei protocolos de SEO e Core Web Vitals para maximizar alcance orgânico, e gerenciei infraestrutura híbrida para garantir escalabilidade de portais de alto tráfego.',
      ],
      techStack: [
        'Full Stack',
        'UI/UX',
        'SEO',
        'Core Web Vitals',
        'Infrastructure',
        'Digital Strategy',
      ],
    },
    {
      company: 'NEXTi SOLUÇÕES EM TECNOLOGIA',
      role: 'Sócio Fundador / Consultor de Software',
      period: 'Jun 2006 – Jan 2015',
      location: 'Caraguatatuba, SP',
      summary: [
        'Fundação e gestão de consultoria de software, desenvolvendo soluções de CRM e CMS sob medida para os setores Imobiliário e de Mídia.',
        'Além dos projetos de software, tive uma loja de informática aberta ao público. A rotina de vender produtos e resolver problemas técnicos na hora me ensinou muito sobre atendimento e a correria real de manter um comércio funcionando.',
        'Essa experiência forneceu uma base sólida em gestão de produtos, liderança de pessoas e métricas de negócios.',
      ],
      techStack: [
        'Full Stack',
        'ASP',
        'PHP',
        'JavaScript',
        'HTML',
        'CSS',
        'SQL',
        'SEO',
        'Web Vitals',
      ],
    },
    {
      isLocked: true,
      company: 'Auto Mecânica SKAR',
      role: 'Mecânico de automóveis',
      period: '2004 – Abril 2006',
      location: 'Caraguatatuba, SP',
      summary: [
        'Compreendi que uma oficina vive de confiança. A responsabilidade de garantir a segurança dos veículos me mostrou que um erro não afeta apenas peças, mas vidas e a reputação do negócio. Essa visão moldou minha ética de trabalho para honrar a fé que os clientes depositavam em nós.',
      ],
      techStack: [
        'Confiança',
        'Responsabilidade',
        'Relacionamento',
        'Precision',
      ],
    },
    {
      isLocked: true,
      company: 'Auto Mecânica SKAR',
      role: 'Auxiliar Administrativo',
      period: '2000 – 2004',
      location: 'Caraguatatuba, SP',
      summary: [
        'Morar sozinho e pagar as próprias contas aos 14 anos foi minha verdadeira escola. Levei essa realidade para o dia a dia da oficina, aprendendo que organização e compromisso eram essenciais não só para o trabalho, mas para a vida.',
      ],
      techStack: [
        'Resposabilidade',
        'Relacionamento',
        'Autonomia',
        'Organização',
        'Compromisso',
      ],
    },
  ],
  education: [
    {
      institution: 'XP EDUCAÇÃO',
      degree: 'Pós-graduação em Arquitetura de Software e Soluções',
      period: 'Em andamento',
    },
    {
      institution: 'PM3',
      degree: 'Product Management',
      period: '2023',
    },
    {
      institution: 'IFSP',
      degree: 'Técnico de Edificações ( Sim, eu fiz edificações )',
      period: '2014 - 2015',
    },
    {
      institution: 'IFSP',
      degree: 'Tecnólogo em Análise e Desenvolvimento de Sistemas',
      period: '2011 - 2013',
    },
    {
      institution: 'Universidade Cruz do Sul',
      degree: 'Tecnólogo Processos Gerenciais',
      period: '2009 - 2010',
    },
    {
      institution: 'CEFET',
      degree: 'Técnico em Desenvolvimento de Sistemas',
      period: '2006 - 2007',
    },
  ],
  ui: {
    greeting: 'Olá, sou',
    about: 'Sobre',
    experience: 'Experiências',
    skills: 'Habilidades',
    education: 'Formação',
    contact: 'Contato',
    achievements: 'Principais Entregas',
    philosophyTitle: 'Filosofia',
    philosophyDesc:
      'Evitar que as escolhas técnicas de hoje se tornem gargalos futuros, alinhando a tecnologia à visão de negócio e garantindo uma evolução sustentável, ágil e contínua do produto.',
    radarTitle: 'Radar de Competências',
    getInTouch: 'Entrar em Contato',
    nonTechExperienceMessage: 'Experiência fora da área de tecnologia',
    unlockButtonLabel: 'Desbloquear experiência',
    unlockButtonText: 'Desbloquear',
  },
  ariaLabels: {
    skipToContent: 'Pular para o conteúdo principal',
    navigateToSection: 'Navegar para seção',
    changeLanguage: 'Alterar idioma',
    currentLanguage: 'Idioma atual',
    sendEmail: 'Enviar email para',
    openWhatsApp: 'Abrir conversa no WhatsApp com',
    openLinkedIn: 'Abrir perfil no LinkedIn em nova aba',
    openInstagram: 'Abrir perfil no Instagram em nova aba',
    openGithub: 'Abrir perfil no GitHub em nova aba',
    contactLinks: 'Links de contato',
    location: 'Localização',
    unlockExperiences: 'Desbloquear experiências não tech',
    experienceTimeline: 'Linha do tempo de experiências profissionais',
    technologiesUsed: 'Tecnologias utilizadas',
    experienceCard: 'Experiência profissional',
    experienceUnlocked: 'Experiência desbloqueada',
    lockedContentDescription:
      'Conteúdo bloqueado, use o botão para desbloquear',
    experienceDescription: 'Descrição da experiência',
    periodLabel: 'Período',
    educationList: 'Formação acadêmica',
    socialLinks: 'Links de redes sociais',
    chartDescription: 'Gráfico radar mostrando habilidades em',
    chartData: 'Dados do gráfico de habilidades',
    skillsCategories: 'Categorias de habilidades',
    skillsInCategory: 'Habilidades em',
    mainNavigation: 'Navegação principal',
    backToTop: 'Voltar ao topo',
    openMenu: 'Abrir menu',
    closeMenu: 'Fechar menu',
    mobileNavigation: 'Menu de navegação mobile',
    personalPresentation: 'Apresentação pessoal',
    srChartDescription: 'Níveis de habilidade por categoria',
    categoryLabel: 'Categoria',
    levelLabel: 'Nível (0-100)',
  },
};

export const DATA_EN: ResumeData = {
  name: 'Andherson Antunes',
  role: 'Staff Software Engineer Frontend | Technical Lead',
  contact: SHARED_CONTACT,
  summary: [
    `With over 10 years of experience in technology, I currently work on the maintenance and evolution of acquisition flow for ZAP and Vivareal at Grupo OLX, 
    eliminating friction in the user journey and designing robust technical solutions that support product growth.`,
    `When I'm offline, I recharge my energy cycling, taking photos, and enjoying moments with my two boys =)`,
  ],
  skillCategories: SKILLS_EN,
  experience: [
    {
      isLocked: true,
      company: 'LIFE',
      role: 'Father',
      period: 'Aug 2021 – Present',
      location: 'On-site',
      summary: [
        "Managing life's most complex and valuable 'project': the future of two human beings.",
        "Responsible for the daily 'deploy' of values, 'debugging' tantrums, and ensuring high availability of affection.",
        'It is the only position where production incidents teach more about emotional intelligence and negotiation than any board meeting.',
      ],
      techStack: [
        'Emotional Intelligence',
        'Negotiation',
        'Crisis Management',
        'Teaching by example',
      ],
    },
    {
      company: 'GRUPO OLX BRASIL',
      role: 'Staff Software Engineer / Front-end Tech Lead',
      period: 'Feb 2024 – Present',
      location: 'Remote',
      summary: [
        'Acting as the technical focal point for the Real Estate vertical (ZAP / Vivareal), bridging the gap between business strategy and engineering execution.',
        'Spearheaded the implementation of code best practices, fostering a quality-first culture and architectural guidelines across various projects.',
        'Mentoring frontend engineers, fostering a culture of autonomy, documentation and automated testing.',
      ],

      techStack: [
        'React.js',
        'Next.js',
        'Vue.js',
        'TypeScript',
        'Micro-frontends',
        'Monorepo',
        'AWS',
        'Datadog',
        'Cypress',
      ],
    },
    {
      company: 'BIONEXO',
      role: 'Tech Lead | Specialist Front-end Developer',
      period: 'Jul 2023 – Feb 2024',
      location: 'Remote',
      summary: [
        'Focused on designing front-end application architectures, establishing development standards and mentoring.',
        'Consolidation of clients from multiple legacy systems and countries into a single, unified global product, reducing complexity and maintenance costs.',
      ],
      techStack: [
        'React.js',
        'Next.js',
        'TypeScript',
        'Playwright',
        'Java',
        'Azure',
        'i18n',
      ],
    },
    {
      company: 'BIONEXO',
      role: 'Systems Analyst (Front-end Engineer)',
      period: 'Sep 2019 – Jul 2023',
      location: 'Remote',
      summary: [
        'Evolution of multiple platform legacy systems.',
        'Worked directly with Product and QA to define requirements.',
        'Agile Leader: Responsible for tracking and managing squad throughput KPIs, and promoting Agile methodologies (Scrum, Kanban, XP).',
      ],
      techStack: [
        'React.js',
        'JSP',
        'jQuery',
        'Ruby on Rails',
        'AWS',
        'Bitbucket',
      ],
    },
    {
      isLocked: true,
      company: 'BADEKAR CENTRO AUTOMOTIVO',
      role: 'Commercial Manager',
      period: 'Oct 2018 – Aug 2019',
      location: 'Caraguatatuba, SP',
      summary: [
        "Led the business's digital transformation, implementing Customer Experience and Digital Marketing processes. Technical role in modernizing inventory management, creating integrations between legacy systems and new web interfaces.",
        'Reverse engineering and middleware development to intercept data from a proprietary system (Delphi), automating inventory management, alongside full-stack development of the corporate website and vehicle history system.',
      ],
      techStack: [
        'Digital Marketing',
        'Web Development',
        'Customer Experience',
        'Middleware',
      ],
    },
    {
      isLocked: true,
      company: 'BANCO BRADESCO SA',
      role: 'From Clerk to Prime Manager',
      period: 'Oct 2011 – Sep 2018',
      location: 'Caraguatatuba, SP',
      summary: [
        'Working in a high-pressure and regulated environment, focusing on agile problem-solving and customer experience.',
        'Dealing with audiences from diverse social classes and life stages taught me empathy, resilience, and clarity in communication—pillars I uphold in my technical leadership.',
      ],
      techStack: [
        'Negotiation',
        'Conflict Management',
        'Consultative Sales',
        'Strategic Communication',
        'Customer Service',
        'Team Leadership',
      ],
    },
    {
      company: 'Beto Biagi Marketing & Comunicação',
      role: 'Full Stack Developer',
      period: 'Aug 2008 - Dec 2009',
      location: 'Atibaia, SP',
      summary: [
        "Acted as the lead technologist for the agency's clients, integrating Engineering, Design, and Ops. A career highlight includes managing the digital presence of Coomex, a major energy asset acquired by BTG Pactual.",
        'Beyond Full Stack development, I led UI/UX initiatives and drove technical performance strategies. Established advanced SEO and Core Web Vitals protocols to maximize organic reach, while managing hybrid infrastructure for high-traffic media vehicles.',
      ],
      techStack: [
        'Full Stack',
        'UI/UX',
        'SEO',
        'Core Web Vitals',
        'Infrastructure',
        'Digital Strategy',
      ],
    },
    {
      company: 'NEXTi SOLUÇÕES EM TECNOLOGIA',
      role: 'Company Owner / Software Consultant',
      period: 'Jun 2006 – Jan 2015',
      location: 'Caraguatatuba, SP',
      summary: [
        'Founded and managed a software consultancy, developing tailored CRM and CMS solutions for Real Estate and Media sectors.',
        'Beyond software projects, I ran a computer store open to the public. The daily routine of selling products and solving technical problems on the spot taught me a lot about customer service and the real hustle of keeping a business running.',
        'This experience provided a solid foundation in product management, people leadership, and business metrics.',
      ],
      techStack: [
        'ASP',
        'PHP',
        'JavaScript',
        'HTML',
        'CSS',
        'SQL',
        'SEO',
        'Web Vitals',
      ],
    },
    {
      isLocked: true,
      company: 'Auto Mecânica SKAR',
      role: 'Automotive Mechanic',
      period: '2004 – Abril 2006',
      location: 'Caraguatatuba, SP',
      summary: [
        'I understood that a repair shop relies on trust. The responsibility of ensuring vehicle safety showed me that an error affects not just parts, but lives and the business reputation. This perspective shaped my work ethic  to honor the faith clients placed in us.',
      ],
      techStack: [
        'Trust',
        'Responsibility',
        'Independence',
        'Relationship',
        'Precision',
      ],
    },
    {
      isLocked: true,
      company: 'Auto Mecânica SKAR',
      role: 'Administrative Assistant',
      period: '2000 – 2004',
      location: 'Caraguatatuba, SP',
      summary: [
        "Living on my own and paying my own bills at 14 was my real school. I brought this reality into the workshop's daily routine, learning that organization and commitment were essential not just for work, but for life.",
      ],
      techStack: [
        'Responsibility',
        'Relationship',
        'Autonomy',
        'Organization',
        'Commitment',
      ],
    },
  ],
  education: [
    {
      institution: 'XP EDUCAÇÃO',
      degree: 'Postgraduate Degree in Software Architecture & Solutions',
      period: 'In Progress',
    },
    {
      institution: 'PM3',
      degree: 'Product Management Certification',
      period: '2023',
    },
    {
      institution: 'IFSP',
      degree: 'Technical in Construction (Yes, I did construction course)',
      period: '2014 - 2015',
    },
    {
      institution: 'IFSP',
      degree: 'Associate Degree in Systems Analysis and Development',
      period: '2011 - 2013',
    },
    {
      institution: 'Universidade Cruz do Sul',
      degree: 'Technical in Process Management',
      period: '2009 - 2010',
    },
    {
      institution: 'CEFET',
      degree: 'Technical training in Systems Development',
      period: '2006 - 2007',
    },
  ],
  ui: {
    greeting: "Hello, I'm",
    about: 'About',
    experience: 'Experiences',
    skills: 'Skills',
    education: 'Education',
    contact: 'Contact',
    achievements: 'Key Achievements',
    philosophyTitle: 'Philosophy',
    philosophyDesc:
      "Prevent today's technical choices from becoming future bottlenecks by aligning technology with the business vision, guaranteeing sustainable, agile, and continuous product evolution.",
    radarTitle: 'Competency Radar',
    getInTouch: 'Get in Touch',
    nonTechExperienceMessage: 'Non-tech experience',
    unlockButtonLabel: 'Unlock experience',
    unlockButtonText: 'Unlock',
  },
  ariaLabels: {
    skipToContent: 'Skip to main content',
    navigateToSection: 'Navigate to section',
    changeLanguage: 'Change language',
    currentLanguage: 'Current language',
    sendEmail: 'Send email to',
    openWhatsApp: 'Open WhatsApp conversation with',
    openLinkedIn: 'Open LinkedIn profile in new tab',
    openInstagram: 'Open Instagram profile in new tab',
    openGithub: 'Open GitHub profile in new tab',
    contactLinks: 'Contact links',
    location: 'Location',
    unlockExperiences: 'Unlock non-tech experiences',
    experienceTimeline: 'Professional experience timeline',
    technologiesUsed: 'Technologies used',
    experienceCard: 'Professional experience',
    experienceUnlocked: 'Experience unlocked',
    lockedContentDescription: 'Locked content, use button to unlock',
    experienceDescription: 'Experience description',
    periodLabel: 'Period',
    educationList: 'Academic education',
    socialLinks: 'Social media links',
    chartDescription: 'Radar chart showing skills in',
    chartData: 'Skills chart data',
    skillsCategories: 'Skill categories',
    skillsInCategory: 'Skills in',
    mainNavigation: 'Main navigation',
    backToTop: 'Back to top',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    mobileNavigation: 'Mobile navigation menu',
    personalPresentation: 'Personal presentation',
    srChartDescription: 'Skill levels by category',
    categoryLabel: 'Category',
    levelLabel: 'Level (0-100)',
  },
};
